-- create_for_smoke_tables.sql
-- Create all output tables for ERTAC EGU postprocessor.
-- CALC_HOURLY_BASE, p.42, same format as CAMD_HOURLY_BASE and
-- ERTAC_HOURLY_NONCAMD in input, with fuel bin added to accomodate units with
-- fuel switches.  Since we had to add the fuel bin, also added ertac_region to
-- make some of the summary stages simpler by reducing table joins.
-- 4/12/2012 Changed relative order of key columns in index.
DROP TABLE IF EXISTS calc_hourly_base;
CREATE TABLE calc_hourly_base
(ertac_region TEXT NOT NULL COLLATE NOCASE,
ertac_fuel_unit_type_bin TEXT NOT NULL COLLATE NOCASE,
state TEXT NOT NULL COLLATE NOCASE,
facility_name TEXT NOT NULL COLLATE NOCASE,
orispl_code TEXT NOT NULL COLLATE NOCASE,
unitid TEXT NOT NULL COLLATE NOCASE,
op_date TEXT NOT NULL,
op_hour INTEGER NOT NULL,
op_time REAL,
gload REAL,
sload REAL,
so2_mass REAL,
so2_mass_flag TEXT,
so2_rate REAL,
so2_rate_flag TEXT,
nox_rate REAL,
nox_rate_flag TEXT,
nox_mass REAL,
nox_mass_flag TEXT,
co2_mass REAL,
co2_mass_flag TEXT,
co2_rate REAL,
co2_rate_flag TEXT,
heat_input REAL,
PRIMARY KEY (ertac_region, ertac_fuel_unit_type_bin, op_date, op_hour, orispl_code, unitid));

-- CALC_UPDATED_UAF, p.43, same format as ERTAC_INITIAL_UAF in input.
DROP TABLE IF EXISTS calc_updated_uaf;
CREATE TABLE calc_updated_uaf
(orispl_code TEXT NOT NULL COLLATE NOCASE,
unitid TEXT NOT NULL COLLATE NOCASE,
form860_plant_id TEXT,
fips_code TEXT,
county_code TEXT,
county_name TEXT,
state TEXT NOT NULL COLLATE NOCASE,
needs_unit_id TEXT,
form860_unit_id TEXT,
plant_latitude REAL,
plant_longitude REAL,
inventory_stack_id TEXT,
facility_name TEXT NOT NULL COLLATE NOCASE,
needs_ipm_region TEXT,
nerc_main_region TEXT,
eia_region_old_nerc TEXT,
ertac_region TEXT NOT NULL COLLATE NOCASE,
other_consuming_regions TEXT,
camd_by_hourly_data_type TEXT NOT NULL COLLATE NOCASE,
annual_hi_partials REAL,
camd_by_operating_status TEXT,
camd_stack_info TEXT,
online_start_date TEXT,
offline_start_date TEXT,
primary_fuel_type TEXT,
main_fuel_characteristics TEXT,
secondary_or_substitute_fuel TEXT,
prime_mover_generator_unit_type TEXT,
camd_unit_type TEXT,
ertac_fuel_unit_type_bin TEXT NOT NULL COLLATE NOCASE,
max_ertac_hi_hourly_summer REAL,
max_ertac_hi_hourly_winter REAL,
hourly_base_max_actual_hi REAL,
nameplate_capacity REAL,
max_summer_capacity REAL,
max_winter_capacity REAL,
max_unit_heat_input REAL,
calculated_by_uf REAL,
max_annual_state_uf REAL,
max_annual_ertac_uf REAL,
operating_hours_by REAL,
max_by_hourly_gload REAL,
max_by_hourly_sload REAL,
nominal_heat_rate REAL,
calc_by_average_heat_rate REAL,
ertac_heat_rate REAL,
unit_annual_capacity_limit REAL,
unit_max_optimal_load_threshold REAL,
unit_min_optimal_load_threshold REAL,
unit_ownership_code TEXT,
multiple_ownership_notation TEXT,
secondary_owner TEXT,
tertiary_owner TEXT,
new_unit_flag TEXT COLLATE NOCASE,
capacity_limited_unit_flag TEXT COLLATE NOCASE,
modifier_email_address TEXT,
unit_completeness_check TEXT,
PRIMARY KEY (orispl_code, unitid, ertac_fuel_unit_type_bin));


-- CALC_INPUT_VARIABLES
-- Same format as ERTAC_INPUT_VARIABLES.
-- 10/6/2011 updates added base year to structure.
DROP TABLE IF EXISTS calc_input_variables;
CREATE TABLE calc_input_variables
(ertac_region TEXT NOT NULL COLLATE NOCASE,
ertac_fuel_unit_type_bin TEXT NOT NULL COLLATE NOCASE,
base_year TEXT NOT NULL,
future_year TEXT NOT NULL,
ozone_start_date TEXT,
ozone_end_date TEXT,
hourly_hierarchy_code TEXT NOT NULL COLLATE NOCASE,
new_unit_max_size INTEGER NOT NULL,
new_unit_min_size INTEGER NOT NULL,
demand_cushion REAL NOT NULL,
facility_1 TEXT COLLATE NOCASE,
facility_2 TEXT COLLATE NOCASE,
facility_3 TEXT COLLATE NOCASE,
facility_4 TEXT COLLATE NOCASE,
facility_5 TEXT COLLATE NOCASE,
facility_6 TEXT COLLATE NOCASE,
facility_7 TEXT COLLATE NOCASE,
facility_8 TEXT COLLATE NOCASE,
facility_9 TEXT COLLATE NOCASE,
facility_10 TEXT COLLATE NOCASE,
maximum_annual_ertac_uf REAL NOT NULL,
capacity_demand_deficit_review INTEGER NOT NULL,
unit_optimal_load_threshold_determinant REAL NOT NULL,
proxy_percentage REAL NOT NULL,
generic_so2_control_efficiency REAL NOT NULL,
generic_scr_nox_rate REAL NOT NULL,
generic_sncr_nox_rate REAL NOT NULL,
new_unit_hierarchy_placement_percentile REAL NOT NULL,
new_unit_emission_factor_percentile REAL NOT NULL,
unit_min_optimal_load_threshold_determinant REAL NOT NULL,
heat_input_calculation_percentile REAL NOT NULL,
PRIMARY KEY (ertac_region, ertac_fuel_unit_type_bin));

CREATE TEMPORARY TABLE fy_emission_rates
(ertac_region TEXT NOT NULL COLLATE NOCASE,
ertac_fuel_unit_type_bin TEXT NOT NULL COLLATE NOCASE,
orispl_code TEXT NOT NULL COLLATE NOCASE,
unitid TEXT NOT NULL COLLATE NOCASE,
pm25_rate REAL,
pm10_rate REAL,
co_rate REAL,
voc_rate REAL,
nh3_rate REAL,
PRIMARY KEY (ertac_region, ertac_fuel_unit_type_bin, orispl_code, unitid),
UNIQUE (ertac_region, ertac_fuel_unit_type_bin, orispl_code, unitid));


DROP TABLE IF EXISTS ertac_pusp_info_file;
CREATE TABLE ertac_pusp_info_file
(ertac_region TEXT NOT NULL COLLATE NOCASE,
ertac_fuel_unit_type_bin TEXT NOT NULL COLLATE NOCASE,
state TEXT,
offline_start_date TEXT,
orispl_code TEXT NOT NULL COLLATE NOCASE,
unitid TEXT NOT NULL COLLATE NOCASE,
plantid TEXT,
pointid TEXT,
stackid TEXT,
segment TEXT,
stkhgt REAL,
stkdiam REAL,
stktemp REAL,
stkflow REAL,
stkvel REAL,
scc TEXT,
time_zone TEXT,
nox_percentage REAL,
so2_percentage REAL,
pm25_percentage REAL,
pm10_percentage REAL,
co_percentage REAL,
voc_percentage REAL,
nh3_percentage REAL,
sic_code REAL,
mact REAL,
naics TEXT,
comments TEXT,
PRIMARY KEY (ertac_region, ertac_fuel_unit_type_bin, state, orispl_code, unitid, plantid, pointid, stackid, segment));

-- Same format as ERTAC_CONTROL_EMISSIONS.
DROP TABLE IF EXISTS ertac_base_year_rates_and_additional_controls;
CREATE TABLE ertac_base_year_rates_and_additional_controls
(orispl_code TEXT NOT NULL COLLATE NOCASE,
unitid TEXT NOT NULL COLLATE NOCASE,
factor_start_date TEXT,
factor_end_date TEXT,
pollutant_code TEXT NOT NULL COLLATE NOCASE,
base_year_rate REAL,
emission_rate REAL,
control_efficiency REAL,
control_programs TEXT,
control_description TEXT,
submitter_email TEXT,
PRIMARY KEY (orispl_code, unitid, pollutant_code));

DROP TABLE IF EXISTS ertac_additional_variables;
CREATE TABLE ertac_additional_variables
(state TEXT NOT NULL COLLATE NOCASE,
ertac_fuel_unit_type_bin TEXT NOT NULL COLLATE NOCASE,
pm25_rate REAL,
pm10_rate REAL,
co_rate REAL,
voc_rate REAL,
nh3_rate REAL,
new_unit_scc TEXT,
new_unit_stkhgt REAL,
new_unit_stkdiam REAL,
new_unit_stktemp REAL,
new_unit_stkflow REAL,
new_unit_stkvel REAL,
comments TEXT,
PRIMARY KEY (state, ertac_fuel_unit_type_bin));

DROP TABLE IF EXISTS hourly_diagnostic_file;
CREATE TABLE hourly_diagnostic_file
(ertac_region TEXT NOT NULL COLLATE NOCASE,
ertac_fuel_unit_type_bin TEXT NOT NULL COLLATE NOCASE,
state TEXT NOT NULL COLLATE NOCASE,
orispl_code TEXT NOT NULL COLLATE NOCASE,
unitid TEXT NOT NULL COLLATE NOCASE,
calendar_hour INTEGER NOT NULL,
hierarchy_hour INTEGER NOT NULL,
hourly_hi_limit TEXT,
annual_hi_limit TEXT,
cumulative_hi REAL,
cumulative_gen REAL,
gload REAL,
heat_input REAL,
so2_mass REAL,
so2_rate REAL,
nox_rate REAL,
nox_mass REAL,
PRIMARY KEY (ertac_region, ertac_fuel_unit_type_bin, hierarchy_hour, orispl_code, unitid),
UNIQUE (ertac_region, calendar_hour, ertac_fuel_unit_type_bin, orispl_code, unitid));

DROP TABLE IF EXISTS orl_future;
CREATE TABLE orl_future
(fips TEXT,
plantid TEXT,
pointid TEXT,
stackid TEXT,
segment TEXT,
plant TEXT,
scc TEXT,
erprtype TEXT,
srctype TEXT,
stkhgt REAL,
stkdiam REAL,
stktemp REAL,
stkflow REAL,
stkvel REAL,
sic_code REAL,
mact REAL,
naics TEXT,
ctype TEXT,
lon REAL,
lat REAL,
utmz REAL,
cas TEXT,
ann_emis REAL,
avd_emis REAL,
ceff REAL,
reff REAL, 
cpri REAL, 
csec REAL, 
nei_unique_id TEXT,
orispl_code TEXT NOT NULL COLLATE NOCASE,
unitid TEXT NOT NULL COLLATE NOCASE,
ipm_yn TEXT,
data_source TEXT,
PRIMARY KEY (plantid, pointid, stackid, segment, orispl_code, unitid, cas));

DROP TABLE IF EXISTS ff10_future;
CREATE TABLE ff10_future
(
country TEXT,
fips TEXT,
tribalcode TEXT,
plantid TEXT,
pointid TEXT,
stackid TEXT,
segment TEXT,
agy_plantid TEXT,
agy_pointid TEXT,
agy_stackid TEXT,
agy_segment TEXT,
scc TEXT,
cas TEXT,
ann_emis REAL,
ann_pct_red TEXT,
plant TEXT,
erprtype TEXT,
stkhgt REAL,
stkdiam REAL,
stktemp REAL,
stkflow REAL,
stkvel REAL,
naics TEXT,
lon REAL,
lat REAL,
ll_datum TEXT,
horiz_coll_mthd TEXT,
design_capacity REAL,
design_capacity_units TEXT,
reg_codes TEXT,
srctype REAL,
unit_typce_cod REAL,
control_ids TEXT,
control_measures TEXT,
current_cost REAL,
cumulative_cost REAL,
projection_fact REAL,
submitter_fac_id TEXT,
calc_method REAL,
data_set_id REAL,
facil_category_code TEXT,
orispl_code TEXT NOT NULL COLLATE NOCASE,
unitid TEXT NOT NULL COLLATE NOCASE,
ipm_yn TEXT,
calc_year TEXT,
date_updated TEXT,
PRIMARY KEY (plantid, pointid, stackid, segment, orispl_code, unitid, cas));

-- Create all output tables for ERTAC EGU postprocessor.
DROP TABLE IF EXISTS pt_hourly_future;
CREATE TABLE pt_hourly_future
(state TEXT NOT NULL COLLATE NOCASE,
county TEXT NOT NULL COLLATE NOCASE,
plantid TEXT,
pointid TEXT,
stackid TEXT,
segment TEXT,
polcode TEXT,
op_date TEXT NOT NULL,
time_zone TEXT,
hrval1 REAL,
hrval2 REAL,
hrval3 REAL,
hrval4 REAL,
hrval5 REAL,
hrval6 REAL,
hrval7 REAL,
hrval8 REAL,
hrval9 REAL,
hrval10 REAL,
hrval11 REAL,
hrval12 REAL,
hrval13 REAL,
hrval14 REAL,
hrval15 REAL,
hrval16 REAL,
hrval17 REAL,
hrval18 REAL,
hrval19 REAL,
hrval20 REAL,
hrval21 REAL,
hrval22 REAL,
hrval23 REAL,
hrval24 REAL,
day_tot REAL,
scc TEXT);

-- Create all output tables for ERTAC EGU postprocessor.
DROP TABLE IF EXISTS ff10_hourly_future;
CREATE TABLE ff10_hourly_future
(
country TEXT NOT NULL COLLATE NOCASE,
fips TEXT NOT NULL COLLATE NOCASE,
tribalcode TEXT,
plantid TEXT,
pointid TEXT,
stackid TEXT,
segment TEXT,
scc TEXT,
polcode TEXT,
op_type_cd TEXT,
calc_method TEXT,
date_updated TEXT,
op_date TEXT NOT NULL,
day_tot REAL,
hrval1 REAL,
hrval2 REAL,
hrval3 REAL,
hrval4 REAL,
hrval5 REAL,
hrval6 REAL,
hrval7 REAL,
hrval8 REAL,
hrval9 REAL,
hrval10 REAL,
hrval11 REAL,
hrval12 REAL,
hrval13 REAL,
hrval14 REAL,
hrval15 REAL,
hrval16 REAL,
hrval17 REAL,
hrval18 REAL,
hrval19 REAL,
hrval20 REAL,
hrval21 REAL,
hrval22 REAL,
hrval23 REAL,
hrval24 REAL,
comment text);