-- create_for_smoke_tables.sql
-- Create all output tables for ERTAC EGU postprocessor.
-- CALC_HOURLY_BASE, p.42, same format as CAMD_HOURLY_BASE and
-- ERTAC_HOURLY_NONCAMD in input, with fuel bin added to accomodate units with
-- fuel switches.  Since we had to add the fuel bin, also added ertac_region to
-- 4/12/2012 Changed relative order of key columns in index.
CREATE TABLE fy_emission_rates
(ertac_region TEXT NOT NULL COLLATE NOCASE,
ertac_fuel_unit_type_bin TEXT NOT NULL COLLATE NOCASE,
orispl_code TEXT NOT NULL COLLATE NOCASE,
unitid TEXT NOT NULL COLLATE NOCASE,
state TEXT,
pm25_rate REAL,
pm25_source TEXT,
pm10_rate REAL,
pm10_source TEXT,
co_rate REAL,
co_source TEXT,
voc_rate REAL,
voc_source TEXT,
nh3_rate REAL,
nh3_source TEXT,
cl2_rate REAL,
cl2_source TEXT,
hcl_rate REAL,
hcl_source TEXT,
PRIMARY KEY (ertac_region, ertac_fuel_unit_type_bin, orispl_code, unitid),
UNIQUE (ertac_region, ertac_fuel_unit_type_bin, orispl_code, unitid, unitid));


DROP TABLE IF EXISTS ertac_pusp_info_file;
CREATE TABLE ertac_pusp_info_file
(ertac_region TEXT NOT NULL COLLATE NOCASE,
ertac_fuel_unit_type_bin TEXT NOT NULL COLLATE NOCASE,
state TEXT,
offline_start_date TEXT,
orispl_code TEXT NOT NULL COLLATE NOCASE,
unitid TEXT NOT NULL COLLATE NOCASE,
plantid TEXT,
pointid TEXT,
stackid TEXT,
segment TEXT,
agy_plantid TEXT,
agy_pointid TEXT,
agy_stackid TEXT,
agy_segment TEXT,
stkhgt REAL,
stkdiam REAL,
stktemp REAL,
stkflow REAL,
stkvel REAL,
scc TEXT,
time_zone TEXT,
nox_percentage REAL,
so2_percentage REAL,
pm25_percentage REAL,
pm10_percentage REAL,
co_percentage REAL,
voc_percentage REAL,
nh3_percentage REAL,
hap_percentage REAL,
sic_code REAL,
mact REAL,
naics TEXT,
comments TEXT,
PRIMARY KEY (ertac_region, ertac_fuel_unit_type_bin, state, orispl_code, unitid, plantid, pointid, stackid, segment));

-- Same format as ERTAC_CONTROL_EMISSIONS.
DROP TABLE IF EXISTS ertac_base_year_rates_and_additional_controls;
CREATE TABLE ertac_base_year_rates_and_additional_controls
(orispl_code TEXT NOT NULL COLLATE NOCASE,
unitid TEXT NOT NULL COLLATE NOCASE,
factor_start_date TEXT,
factor_end_date TEXT,
pollutant_code TEXT NOT NULL COLLATE NOCASE,
base_year_rate REAL,
emission_rate REAL,
control_efficiency REAL,
control_programs TEXT,
control_description TEXT,
submitter_email TEXT);

DROP TABLE IF EXISTS ertac_additional_variables;
CREATE TABLE ertac_additional_variables
(state TEXT NOT NULL COLLATE NOCASE,
ertac_fuel_unit_type_bin TEXT NOT NULL COLLATE NOCASE,
pm25_rate REAL,
pm10_rate REAL,
co_rate REAL,
voc_rate REAL,
nh3_rate REAL,
cl2_rate REAL,
hcl_rate REAL,
new_unit_scc TEXT,
new_unit_stkhgt REAL,
new_unit_stkdiam REAL,
new_unit_stktemp REAL,
new_unit_stkflow REAL,
new_unit_stkvel REAL,
comments TEXT,
PRIMARY KEY (state, ertac_fuel_unit_type_bin));

DROP TABLE IF EXISTS ertac_rpo_listing;
CREATE TABLE ertac_rpo_listing
(rpo TEXT NOT NULL COLLATE NOCASE,
states TEXT NOT NULL COLLATE NOCASE);

DROP TABLE IF EXISTS orl_future;
CREATE TABLE orl_future
(fips TEXT,
plantid TEXT,
pointid TEXT,
stackid TEXT,
segment TEXT,
plant TEXT,
scc TEXT,
erprtype TEXT,
srctype TEXT,
stkhgt REAL,
stkdiam REAL,
stktemp REAL,
stkflow REAL,
stkvel REAL,
sic_code REAL,
mact REAL,
naics TEXT,
ctype TEXT,
lon REAL,
lat REAL,
utmz REAL,
cas TEXT,
ann_emis REAL,
avd_emis REAL,
ceff REAL,
reff REAL, 
cpri REAL, 
csec REAL, 
nei_unique_id TEXT,
orispl_code TEXT NOT NULL COLLATE NOCASE,
unitid TEXT NOT NULL COLLATE NOCASE,
ipm_yn TEXT,
data_source TEXT,
PRIMARY KEY (plantid, pointid, stackid, segment, orispl_code, unitid, cas));

DROP TABLE IF EXISTS ff10_future;
CREATE TABLE ff10_future
(
country TEXT,
fips TEXT,
tribalcode TEXT,
plantid TEXT,
pointid TEXT,
stackid TEXT,
segment TEXT,
agy_plantid TEXT,
agy_pointid TEXT,
agy_stackid TEXT,
agy_segment TEXT,
scc TEXT,
cas TEXT,
ann_emis REAL,
ann_pct_red REAL,
plant TEXT,
erprtype TEXT,
stkhgt REAL,
stkdiam REAL,
stktemp REAL,
stkflow REAL,
stkvel REAL,
naics TEXT,
lon REAL,
lat REAL,
ll_datum TEXT,
horiz_coll_mthd TEXT,
design_capacity REAL,
design_capacity_units TEXT,
reg_codes TEXT,
srctype TEXT,
unit_typce_cod TEXT,
control_ids TEXT,
control_measures TEXT,
current_cost REAL,
cumulative_cost REAL,
projection_fact REAL,
submitter_fac_id TEXT,
calc_method REAL,
data_set_id TEXT,
facil_category_code TEXT,
orispl_code TEXT NOT NULL COLLATE NOCASE,
unitid TEXT NOT NULL COLLATE NOCASE,
ipm_yn TEXT,
calc_year TEXT,
date_updated INTEGER,
fug_height REAL,
fug_width_ydim REAL,
fug_length_xdim REAL,
fug_angle REAL,
zipcode TEXT,
annual_avg_hours_per_year REAL,
jan_value REAL DEFAULT 0,
feb_value REAL DEFAULT 0,
mar_value REAL DEFAULT 0,
apr_value REAL DEFAULT 0,
may_value REAL DEFAULT 0,
jun_value REAL DEFAULT 0,
jul_value REAL DEFAULT 0,
aug_value REAL DEFAULT 0,
sep_value REAL DEFAULT 0,
oct_value REAL DEFAULT 0,
nov_value REAL DEFAULT 0,
dec_value REAL DEFAULT 0,
jan_pctred REAL,
feb_pctred REAL,
mar_pctred REAL,
apr_pctred REAL,
may_pctred REAL,
jun_pctred REAL,
jul_pctred REAL,
aug_pctred REAL,
sep_pctred REAL,
oct_pctred REAL,
nov_pctred REAL,
dec_pctred REAL,
comment TEXT,
PRIMARY KEY (plantid, pointid, stackid, segment, orispl_code, unitid, scc, cas, facil_category_code));

-- Create all output tables for ERTAC EGU postprocessor.
DROP TABLE IF EXISTS pt_hourly_future;
CREATE TABLE pt_hourly_future
(state TEXT NOT NULL COLLATE NOCASE,
county TEXT NOT NULL COLLATE NOCASE,
plantid TEXT,
pointid TEXT,
stackid TEXT,
segment TEXT,
polcode TEXT,
op_date TEXT NOT NULL,
time_zone TEXT,
hrval1 REAL DEFAULT 0,
hrval2 REAL DEFAULT 0,
hrval3 REAL DEFAULT 0,
hrval4 REAL DEFAULT 0,
hrval5 REAL DEFAULT 0,
hrval6 REAL DEFAULT 0,
hrval7 REAL DEFAULT 0,
hrval8 REAL DEFAULT 0,
hrval9 REAL DEFAULT 0,
hrval10 REAL DEFAULT 0,
hrval11 REAL DEFAULT 0,
hrval12 REAL DEFAULT 0,
hrval13 REAL DEFAULT 0,
hrval14 REAL DEFAULT 0,
hrval15 REAL DEFAULT 0,
hrval16 REAL DEFAULT 0,
hrval17 REAL DEFAULT 0,
hrval18 REAL DEFAULT 0,
hrval19 REAL DEFAULT 0,
hrval20 REAL DEFAULT 0,
hrval21 REAL DEFAULT 0,
hrval22 REAL DEFAULT 0,
hrval23 REAL DEFAULT 0,
hrval24 REAL DEFAULT 0,
day_tot REAL DEFAULT 0,
scc TEXT);

-- Create all output tables for ERTAC EGU postprocessor.
DROP TABLE IF EXISTS ff10_hourly_future;
CREATE TABLE ff10_hourly_future
(
country TEXT NOT NULL COLLATE NOCASE,
fips TEXT NOT NULL COLLATE NOCASE,
tribalcode TEXT,
plantid TEXT,
pointid TEXT,
stackid TEXT,
segment TEXT,
scc TEXT,
polcode TEXT,
op_type_cd TEXT,
calc_method TEXT,
date_updated INTEGER,
op_date TEXT NOT NULL,
day_tot REAL DEFAULT 0,
hrval1 REAL DEFAULT 0,
hrval2 REAL DEFAULT 0,
hrval3 REAL DEFAULT 0,
hrval4 REAL DEFAULT 0,
hrval5 REAL DEFAULT 0,
hrval6 REAL DEFAULT 0,
hrval7 REAL DEFAULT 0,
hrval8 REAL DEFAULT 0,
hrval9 REAL DEFAULT 0,
hrval10 REAL DEFAULT 0,
hrval11 REAL DEFAULT 0,
hrval12 REAL DEFAULT 0,
hrval13 REAL DEFAULT 0,
hrval14 REAL DEFAULT 0,
hrval15 REAL DEFAULT 0,
hrval16 REAL DEFAULT 0,
hrval17 REAL DEFAULT 0,
hrval18 REAL DEFAULT 0,
hrval19 REAL DEFAULT 0,
hrval20 REAL DEFAULT 0,
hrval21 REAL DEFAULT 0,
hrval22 REAL DEFAULT 0,
hrval23 REAL DEFAULT 0,
hrval24 REAL DEFAULT 0,
comment text);

DROP TABLE IF EXISTS annual_summary_with_other_pollutants;
CREATE TABLE annual_summary_with_other_pollutants
(orispl_code TEXT NOT NULL COLLATE NOCASE,
unitid TEXT NOT NULL COLLATE NOCASE,
facility_name TEXT COLLATE NOCASE,
state TEXT COLLATE NOCASE,
fips_code TEXT COLLATE NOCASE,
ertac_region TEXT NOT NULL COLLATE NOCASE,
ertac_fuel_unit_type_bin TEXT NOT NULL COLLATE NOCASE,
by_ertac_fuel_unit_type_bin TEXT NOT NULL COLLATE NOCASE,
max_unit_heat_input REAL,
ertac_heat_rate REAL,
generation_capacity REAL,
nameplate_capacity REAL,
fy_op_hours INTEGER,
fy_op_hours_max INTEGER,
by_uf REAL,
fy_uf REAL,
by_gload REAL,
by_heat_input REAL,
fy_gload REAL,
fy_heat_input REAL,
by_so2_mass REAL,
by_so2_rate REAL,
by_nox_mass REAL,
by_nox_rate REAL,
by_os_nox_mass REAL,
by_os_nox_rate REAL,
by_os_heat_input REAL,
by_os_gload REAL,
by_non_os_nox_mass REAL,
by_non_os_nox_rate REAL,
by_co2_mass REAL,
by_co2_rate REAL,
fy_so2_mass REAL,
fy_so2_rate REAL,
fy_so2_max REAL,
fy_nox_mass REAL,
fy_nox_rate REAL,
fy_nox_max REAL,
fy_os_nox_mass REAL,
fy_os_nox_rate REAL,
fy_os_heat_input REAL,
fy_os_gload REAL,
fy_non_os_nox_mass REAL,
fy_non_os_nox_rate REAL,
fy_co2_mass REAL,
fy_co2_rate REAL,
hierarchy_order INTEGER,
longitude REAL,
latitude REAL,
gdu_flag TEXT,
retirement_date TEXT,
new_unit_flag TEXT,
data_type TEXT COLLATE NOCASE,
program_codes TEXT,
fy_pm25_mass REAL,
fy_pm25_rate REAL,
fy_pm10_mass REAL,
fy_pm10_rate REAL,
fy_co_mass REAL,
fy_co_rate REAL,
fy_voc_mass REAL,
fy_voc_rate REAL,
fy_nh3_mass REAL,
fy_nh3_rate REAL,
fy_cl2_mass REAL,
fy_cl2_rate REAL,
fy_hcl_mass REAL,
fy_hcl_rate REAL,
PRIMARY KEY (ertac_region, ertac_fuel_unit_type_bin,  orispl_code, unitid),
UNIQUE (ertac_region, ertac_fuel_unit_type_bin, orispl_code, unitid));