-- create_postprocessing_tables.sql

-- Create all output tables for ERTAC EGU postprocessor.

DROP TABLE IF EXISTS hourly_activity_summary;
CREATE TABLE hourly_activity_summary
(ertac_region TEXT NOT NULL COLLATE NOCASE,
ertac_fuel_unit_type_bin TEXT NOT NULL COLLATE NOCASE,
by_ertac_fuel_unit_type_bin TEXT NOT NULL COLLATE NOCASE,
orispl_code TEXT NOT NULL COLLATE NOCASE,
unitid TEXT NOT NULL COLLATE NOCASE,
state TEXT NOT NULL COLLATE NOCASE,
calendar_hour INTEGER NOT NULL,
hierarchy_hour INTEGER,
hourly_hi_limit TEXT NOT NULL COLLATE NOCASE,
by_hierarchy_hour INTEGER,
by_gload REAL,
fy_gload REAL,
by_heat_input REAL,
fy_heat_input REAL,
by_so2_mass REAL,
fy_so2_mass REAL,
by_nox_mass REAL,
fy_nox_mass REAL,
hour_specific_growth_rate REAL,
afygr REAL,
data_type TEXT COLLATE NOCASE,
facility_name TEXT COLLATE NOCASE,
PRIMARY KEY (ertac_region, ertac_fuel_unit_type_bin, orispl_code, unitid, calendar_hour),
UNIQUE (ertac_region, calendar_hour, ertac_fuel_unit_type_bin, orispl_code, unitid));


DROP TABLE IF EXISTS daily_unit_activity_summary;
CREATE TABLE daily_unit_activity_summary
(ertac_region TEXT NOT NULL COLLATE NOCASE,
ertac_fuel_unit_type_bin TEXT NOT NULL COLLATE NOCASE,
by_ertac_fuel_unit_type_bin TEXT NOT NULL COLLATE NOCASE,
orispl_code TEXT NOT NULL COLLATE NOCASE,
unitid TEXT NOT NULL COLLATE NOCASE,
state TEXT NOT NULL COLLATE NOCASE,
calendar_day TEXT NOT NULL,
by_gload REAL,
fy_gload REAL,
by_heat_input REAL,
fy_heat_input REAL,
by_so2_mass REAL,
fy_so2_mass REAL,
by_nox_mass REAL,
fy_nox_mass REAL,
data_type TEXT COLLATE NOCASE,
facility_name TEXT COLLATE NOCASE,
PRIMARY KEY (ertac_region, ertac_fuel_unit_type_bin, orispl_code, unitid, calendar_day),
UNIQUE (ertac_region, calendar_day, ertac_fuel_unit_type_bin, orispl_code, unitid));


DROP TABLE IF EXISTS hourly_regional_activity_summary;
CREATE TABLE hourly_regional_activity_summary
(ertac_region TEXT NOT NULL COLLATE NOCASE,
ertac_fuel_unit_type_bin TEXT NOT NULL COLLATE NOCASE,
data_type TEXT COLLATE NOCASE,
calendar_hour INTEGER NOT NULL,
hierarchy_hour INTEGER NOT NULL,
by_gload REAL,
fy_gload REAL,
fy_op_max_count REAL,
by_heat_input REAL,
fy_heat_input REAL,
by_so2_mass REAL,
fy_so2_mass REAL,
by_nox_mass REAL,
fy_nox_mass REAL,
hour_specific_growth_rate REAL,
afygr REAL,
PRIMARY KEY (ertac_region, ertac_fuel_unit_type_bin, data_type, calendar_hour),
UNIQUE (ertac_region, calendar_hour, ertac_fuel_unit_type_bin, data_type));

DROP TABLE IF EXISTS hourly_state_activity_summary;
CREATE TABLE hourly_state_activity_summary
(state TEXT NOT NULL COLLATE NOCASE,
ertac_fuel_unit_type_bin TEXT NOT NULL COLLATE NOCASE,
calendar_hour INTEGER NOT NULL,
by_gload REAL,
fy_gload REAL,
by_heat_input REAL,
fy_heat_input REAL,
by_so2_mass REAL,
fy_so2_mass REAL,
by_nox_mass REAL,
fy_nox_mass REAL,
PRIMARY KEY (state, ertac_fuel_unit_type_bin, calendar_hour),
UNIQUE (state, ertac_fuel_unit_type_bin, calendar_hour));

DROP TABLE IF EXISTS annual_summary;
CREATE TABLE annual_summary
(orispl_code TEXT NOT NULL COLLATE NOCASE,
unitid TEXT NOT NULL COLLATE NOCASE,
facility_name TEXT COLLATE NOCASE,
state TEXT COLLATE NOCASE,
fips_code TEXT COLLATE NOCASE,
ertac_region TEXT NOT NULL COLLATE NOCASE,
ertac_fuel_unit_type_bin TEXT NOT NULL COLLATE NOCASE,
by_ertac_fuel_unit_type_bin TEXT NOT NULL COLLATE NOCASE,
max_unit_heat_input REAL,
ertac_heat_rate REAL,
generation_capacity REAL,
nameplate_capacity REAL,
fy_op_hours INTEGER,
fy_op_hours_max INTEGER,
by_uf REAL,
fy_uf REAL,
by_gload REAL,
by_heat_input REAL,
fy_gload REAL,
fy_heat_input REAL,
by_so2_mass REAL,
by_so2_rate REAL,
by_nox_mass REAL,
by_nox_rate REAL,
by_os_nox_mass REAL,
by_os_nox_rate REAL,
by_os_heat_input REAL,
by_os_gload REAL,
by_non_os_nox_mass REAL,
by_non_os_nox_rate REAL,
fy_so2_mass REAL,
fy_so2_rate REAL,
fy_so2_max REAL,
fy_nox_mass REAL,
fy_nox_rate REAL,
fy_nox_max REAL,
fy_os_nox_mass REAL,
fy_os_nox_rate REAL,
fy_os_heat_input REAL,
fy_os_gload REAL,
fy_non_os_nox_mass REAL,
fy_non_os_nox_rate REAL,
hierarchy_order INTEGER,
longitude REAL,
latitude REAL,
gdu_flag TEXT,
retirement_date TEXT,
new_unit_flag TEXT,
data_type TEXT COLLATE NOCASE,
program_codes TEXT,
PRIMARY KEY (ertac_region, ertac_fuel_unit_type_bin,  orispl_code, unitid),
UNIQUE (ertac_region, ertac_fuel_unit_type_bin, orispl_code, unitid));

-- CALC_GENERATION_PARMS, p.53
DROP TABLE IF EXISTS generation_parms;
CREATE TABLE generation_parms
(ertac_region TEXT NOT NULL COLLATE NOCASE,
ertac_fuel_unit_type_bin TEXT NOT NULL COLLATE NOCASE,
op_date TEXT NOT NULL,
op_hour INTEGER NOT NULL,
temporal_allocation_order INTEGER NOT NULL,
hour_specific_growth_rate REAL,
base_actual_generation REAL,
base_retired_generation REAL,
future_projected_generation REAL,
future_projected_growth REAL,
total_proxy_generation REAL,
adjusted_projected_generation REAL,
afygr REAL,
excess_generation_pool REAL,
PRIMARY KEY (ertac_region, ertac_fuel_unit_type_bin, op_date, op_hour),
UNIQUE (ertac_region, ertac_fuel_unit_type_bin, temporal_allocation_order));